### PR TITLE
Frame buffer pallet

### PR DESCRIPTION
**Pull request by KurtE**

### CODE REVIEW

**Comment by mjs513** [comment]
Thanks Kurt
Have to do in morning . 

Mike

**Comment by KurtE** [comment]
I think I may try it the old fashion way... 

Will close when it is done.

**Comment by mjs513** [comment]
Kurt
Went ahead and incorporated your changes into the master.  Tested on the T$

**Comment by KurtE** [comment]
Closed out as done with other ...

**Pull request closed without merging**
