### PR TITLE
Fix example

### PR DESCRIPTION
**Pull request by KurtE**
@PaulStoffregen @mjs513:
Keyboard object no longer top level object, but HID object

But tempted to just toss the example and/or remove everything not Tablet.   I personally don't care one way or the other as the digitizer class is rather limited in usage as it works with very few tablets.  Maybe at some day integrate in our Wacom version instead.  But at this point not inspired

Looking at a couple of compiler warning with beta build in usbhost_t36.

### CODE REVIEW

**Comment by mjs513** [comment]
To be honest - the digitizer class really has been superceded by the Wacom version so probably would just ditch the example.

**Comment by KurtE** [comment]
@PaulStoffregen - We found a few more warnings in that sketch that @mjs513 merged in the changes after this pull.

Another wishlist.  Pull all of these drivers out of Teensyduino and Board installs.   Wish there was another central GITHUB account like:  PJRC, or Teensy_drivers or the like, where all non-central libraries like this, would then be added to the Arduino Library Manager, like the Adafruit or Sparkfun ones are... 

Also one could then setup rules on github to build all of the examples for all of the appropriate boards.
A pjrc forum member has done PRs to me to setup ili9341_t3n to run on all examples.  I probably should enable it.

Now back to something.

**Comment by PaulStoffregen** [comment]
I pulled in the latest, in prep for 1.58

**Comment by mjs513** [comment]
@PaulStoffregen - @KurtE 
Just want to make sure to you got the changes to the RA8875_t4 as well.  Did see them in your fork for some reason the other day

**Comment by PaulStoffregen** [comment]
Yes.  Latest commit in my copy is "Updated digitizer4 w/additional Kurt Changes".

**Pull request merged**
